version: '3.9'

services:
  django:
    build: .
    container_name: django
    env_file:
      - .env
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/KinoCMS
      - media:/KinoCMS/media
    labels:
      - "traefik.http.routers.django_app.rule=Host(`vgg0c0sswwcowo488wk80kkg.78.141.224.252.sslip.io`)"
      - "traefik.http.routers.django_app.entrypoints=web"
      - "traefik.http.services.django_app.loadbalancer.server.port=8000"
      - "traefik.http.services.django_app.loadbalancer.server.responseTimeout=60s" # Тайм-аут для Traefik
      - "traefik.http.services.django_app.loadbalancer.server.readTimeout=60s"      # Додавання тайм-аутів читання
      - "traefik.http.services.django_app.loadbalancer.server.forwardedHeaders.insecure=true" # Для роботи з зашифрованими з'єднаннями
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis
    networks:
      - webnet

  db:
    image: mysql:latest
    container_name: db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: 'sandora12345'
      MYSQL_DATABASE: 'root'
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql

  celery:
    build: .
    command: ["celery", "-A", "config", "worker", "--loglevel=info"]
    env_file:
      - .env
    volumes:
      - .:/KinoCMS
    depends_on:
      - db
      - redis

  redis:
    image: "redis:alpine"

  media:
    image: nginx:alpine
    container_name: media
    volumes:
      - media:/KinoCMS/media
    labels:
      - "traefik.http.routers.media.rule=Host(`vgg0c0sswwcowo488wk80kkg.78.141.224.252.sslip.io`) && PathPrefix(`/media`)"
      - "traefik.http.services.media.loadbalancer.server.port=80"
      - "traefik.http.routers.media.entrypoints=web"  # Додано точку входу для media
    networks:
      - webnet

networks:
  webnet:

volumes:
  media:
    driver: local
  db_data:
