version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate
      && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/KinoCMS
    ports:
      - "8001:8000"
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - mynetwork

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "config", "worker", "--loglevel=info"]
    volumes:
      - .:/KinoCMS
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - mynetwork

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env.prod
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "--silent" ]
      interval: 10s
      timeout: 5s
      retries: 5


  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
  redis_data:

networks:
  mynetwork:
