version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "./wait-for-it.sh db:3306 --
      && python manage.py migrate
      && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./src:/KinoCMS/src
      - ./wait-for-it.sh:/wait-for-it.sh
    ports:
      - "8001:8000"
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
    networks:
      - mynetwork

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "config", "worker", "--loglevel=info"]
    volumes:
      - ./src:/KinoCMS/src
    depends_on:
      - redis
      - db
    env_file:
      - .env.prod
    networks:
      - mynetwork

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "config", "beat", "--loglevel=info"]
    volumes:
      - ./src:/KinoCMS/src
    depends_on:
      - redis
      - db
    env_file:
      - .env.prod
    networks:
      - mynetwork

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Kino_DB_backup.sql:/docker-entrypoint-initdb.d/dump.sql
    env_file:
      - .env.prod
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data
    networks:
      - mynetwork

volumes:
  mysql_data:
  redis_data:

networks:
  mynetwork:
