version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"]
    volumes:
      - .:/KinoCMS
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - mynetwork

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "config", "worker", "--loglevel=info"]
    volumes:
      - .:/KinoCMS
    depends_on:
      - redis
      - db
    env_file:
      - .env
    networks:
      - mynetwork

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "config", "beat", "--loglevel=info"]
    volumes:
      - .:/KinoCMS
    depends_on:
      - redis
      - db
    env_file:
      - .env
    networks:
      - mynetwork

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data
    networks:
      - mynetwork

volumes:
  mysql_data:
  redis_data:

networks:
  mynetwork:
