# Generated by Django 5.0.6 on 2024-07-27 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_galleryimage_image_url'),
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('seomixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.seomixin')),
                ('name', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('link', models.URLField()),
                ('type', models.CharField(choices=[('news', 'Новина'), ('prom', 'Акція')], max_length=4)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gallery')),
                ('main_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_image_for', to='core.galleryimage')),
            ],
            bases=('core.seomixin', models.Model),
        ),
        migrations.DeleteModel(
            name='NewsPromotion',
        ),
    ]
