# Generated by Django 5.0.6 on 2024-09-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0005_post_description_en_post_description_uk_post_name_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description_uk',
            new_name='description_ua',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='name_uk',
            new_name='name_ua',
        ),
    ]
