# Generated by Django 5.0.6 on 2024-07-30 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_remove_galleryimage_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('seomixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.seomixin')),
                ('status', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('seo_text_main_page', models.TextField()),
            ],
            bases=('core.seomixin', models.Model),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('seomixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.seomixin')),
                ('name', models.CharField(max_length=12, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gallery')),
                ('main_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_banner', to='core.galleryimage')),
            ],
            bases=('core.seomixin', models.Model),
        ),
    ]
