# Generated by Django 5.0.6 on 2024-07-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
