# Generated by Django 5.0.6 on 2024-07-31 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pages', '0002_contacts'),
        ('core', '0006_remove_galleryimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='seo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.seomixin'),
        ),
    ]
