# Generated by Django 5.0.6 on 2024-07-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pages', '0002_alter_page_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='contacts',
            name='coordinates_lat',
            field=models.CharField(default=0, max_length=12),
        ),
        migrations.AddField(
            model_name='contacts',
            name='coordinates_long',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
