# Generated by Django 5.0.6 on 2024-08-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pages', '0003_contacts_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
