# Generated by Django 5.0.6 on 2024-07-27 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pages', '0003_remove_contacts_coordinates_contacts_coordinates_lat_and_more'),
        ('core', '0006_remove_galleryimage_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('seomixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.seomixin')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('seo_text_main_page', models.TextField()),
            ],
            bases=('core.seomixin', models.Model),
        ),
    ]
