# Generated by Django 5.0.6 on 2024-09-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pages', '0004_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='name_en',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='page',
            name='name_uk',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
