# Generated by Django 5.0.6 on 2024-07-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pages', '0004_mainpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
