# Generated by Django 5.0.6 on 2024-09-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pages', '0005_page_description_en_page_description_uk_page_name_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='description_uk',
            new_name='description_ua',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='name_uk',
            new_name='name_ua',
        ),
    ]
