# Generated by Django 5.0.6 on 2024-07-01 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('seomixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.seomixin')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('title', models.TextField()),
                ('city', models.CharField(max_length=12)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gallery')),
                ('logo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cinema_logo', to='core.galleryimage')),
                ('main_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cinema_main_image', to='core.galleryimage')),
            ],
            bases=('core.seomixin', models.Model),
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('seomixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.seomixin')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('IMAX', 'IMAX'), ('2D', '2D'), ('3D', '3D')], max_length=8)),
                ('schema', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gallery')),
                ('main_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hall_main_image', to='core.galleryimage')),
                ('schema_picture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hall_schema_picture', to='core.galleryimage')),
            ],
            bases=('core.seomixin', models.Model),
        ),
    ]
