# Generated by Django 5.0.6 on 2024-07-22 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0002_remove_hall_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='cinema_hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='cinemas.cinema'),
        ),
    ]
