# Generated by Django 5.0.6 on 2024-07-22 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0003_hall_cinema_hall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall',
            old_name='schema',
            new_name='schema_json',
        ),
    ]
