# Generated by Django 5.0.6 on 2024-09-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0005_cinema_slug_hall_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='name_en',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='name_uk',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='title_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='title_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='name_en',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='name_uk',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
