# Generated by Django 5.0.6 on 2024-09-10 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0007_rename_name_uk_cinema_name_ua_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinema',
            old_name='name_ua',
            new_name='name_uk',
        ),
        migrations.RenameField(
            model_name='cinema',
            old_name='title_ua',
            new_name='title_uk',
        ),
        migrations.RenameField(
            model_name='hall',
            old_name='description_ua',
            new_name='description_uk',
        ),
        migrations.RenameField(
            model_name='hall',
            old_name='name_ua',
            new_name='name_uk',
        ),
    ]
