# Generated by Django 5.0.6 on 2024-09-11 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0008_rename_name_ua_cinema_name_uk_and_more'),
        ('core', '0006_remove_galleryimage_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinema',
            old_name='title',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='cinema',
            old_name='title_en',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='cinema',
            old_name='title_uk',
            new_name='description_uk',
        ),
        migrations.AlterField(
            model_name='cinema',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gallery'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gallery'),
        ),
    ]
