# Generated by Django 5.0.6 on 2024-07-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_mainpagebanners_mainpagenewsbanners_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagebanners',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainpagenewsbanners',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
