# Generated by Django 5.0.6 on 2024-07-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_backgroundbanner_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundbanner',
            name='back',
            field=models.CharField(choices=[('css', 'css фото'), ('photo', 'фото')], max_length=12),
        ),
    ]
