# Generated by Django 5.0.6 on 2024-08-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0005_alter_backgroundbanner_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagebanners',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='mainpagenewsbanners',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
