# Generated by Django 5.0.6 on 2024-08-26 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0006_mainpagebanners_url_mainpagenewsbanners_url'),
        ('core', '0006_remove_galleryimage_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpagebanners',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='mainpagebanners',
            name='url',
        ),
        migrations.RemoveField(
            model_name='mainpagenewsbanners',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='mainpagenewsbanners',
            name='url',
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=100, null=True)),
                ('gallery_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.galleryimage')),
                ('main_page_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_images', to='banners.mainpagebanners')),
                ('news_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_images', to='banners.mainpagenewsbanners')),
            ],
        ),
    ]
