# Generated by Django 5.0.6 on 2024-08-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='movie_type',
            field=models.CharField(choices=[('IMAX', 'IMAX'), ('2D', '2D'), ('3D', '3D')], default='3D', max_length=4),
        ),
    ]
