# Generated by Django 5.0.6 on 2024-08-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0002_showtime_movie_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.AddField(
            model_name='showtime',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
