# Generated by Django 5.0.6 on 2024-07-01 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SEOMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_seo', models.URLField()),
                ('title_seo', models.CharField(max_length=20)),
                ('keywords_seo', models.CharField(max_length=20)),
                ('description_seo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='gallery/')),
                ('url', models.URLField()),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gallery')),
            ],
        ),
    ]
