# Generated by Django 5.0.6 on 2024-07-05 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_galleryimage_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='url',
            new_name='image',
        ),
    ]
