# Generated by Django 5.0.6 on 2024-07-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_url_galleryimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='image',
            new_name='image_url',
        ),
    ]
