# Generated by Django 5.0.6 on 2024-07-07 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_galleryimage_image_alter_galleryimage_gallery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='image_url',
        ),
    ]
