# Generated by Django 5.0.6 on 2024-08-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useremailcampaign',
            old_name='email_campaign_id',
            new_name='email_campaign',
        ),
        migrations.RenameField(
            model_name='useremailcampaign',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
