# Generated by Django 5.0.6 on 2024-08-15 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_rename_email_campaign_id_useremailcampaign_email_campaign_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='send_to_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='email_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserEmailCampaign',
        ),
    ]
