# Generated by Django 5.0.6 on 2024-08-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_emailcampaign_send_to_all_emailcampaign_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcampaign',
            name='users',
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='selected_users_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
