# Generated by Django 5.0.6 on 2024-08-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_remove_emailcampaign_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcampaign',
            name='created_at',
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='sent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='selected_users_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
