# Generated by Django 5.0.6 on 2024-08-16 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_remove_emailcampaign_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='selected_users_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
