# Generated by Django 5.0.6 on 2024-07-01 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('seomixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.seomixin')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('title', models.TextField()),
                ('year', models.IntegerField(db_index=True)),
                ('country', models.CharField(max_length=20)),
                ('composer', models.CharField(max_length=20)),
                ('produser', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=20)),
                ('screenwriter', models.CharField(max_length=20)),
                ('operator', models.CharField(max_length=20)),
                ('budget', models.FloatField()),
                ('age', models.CharField(choices=[('14+', '14+'), ('16+', '16+'), ('18+', '18+')], max_length=3)),
                ('time', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=20)),
                ('trailer', models.URLField()),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gallery')),
                ('main_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_image_for_movie', to='core.galleryimage')),
            ],
            bases=('core.seomixin', models.Model),
        ),
    ]
