# Generated by Django 5.0.6 on 2024-07-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='age',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='composer',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='country',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='produser',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='screenwriter',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='time',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
    ]
