# Generated by Django 5.0.6 on 2024-08-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_title_movie_description_remove_movie_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
