# Generated by Django 5.0.6 on 2024-09-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_remove_movie_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='name_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='name_uk',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
