# Generated by Django 5.0.6 on 2024-09-11 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_galleryimage_image_url'),
        ('movies', '0010_movie_description_en_movie_description_uk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gallery'),
        ),
    ]
